<?= $this->doctype()
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <link rel="stylesheet" type="text/css" href="/dhtmlx/dhtmlx.css" />
        <link rel="stylesheet" type="text/css" href="/dhtmlx/dhtmlxtabbar.css" />
        <link rel="stylesheet" type="text/css" href="/dhtmlx/dhtmlxtree.css" />
        <link rel="stylesheet" type="text/css" href="/dhtmlx/dhtmlxlayout.css" />
        <link rel="stylesheet" type="text/css" href="/dhtmlx/dhtmlxvault.css" />
        <link rel="stylesheet" type="text/css" href="/dhtmlx/skins/dhtmlxlayout_dhx_skyblue.css" />
        <?= FileManager::generateCSSHeaders() ?>
        <script type="text/javascript" src="/dhtmlx/dhtmlx.js"></script>
        <script type="text/javascript" src="/dhtmlx/dhtmlxtabbar.js"></script>
        <script type="text/javascript" src="/dhtmlx/dhtmlxtree.js"></script>
        <script type="text/javascript" src="/dhtmlx/dhtmlxcontainer.js"></script>
        <script type="text/javascript" src="/dhtmlx/dhtmlxlayout.js"></script>
        <script type="text/javascript" src="/dhtmlx/dhtmlxvault.js"></script>
        <script type="text/javascript" src="/dhtmlx/connector.js"></script>
        <script type="text/javascript" src="/application.js"></script>
        <?= FileManager::generateJSHeaders() ?>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?= Translator::_('SYSTEM_TITLE')
?></title>
    </head>
    <body onLoad="javascript: init()">
        <div id="desktop" style="border: 1px solid gray;"></div>
        <div id="bar">
            <div id="start" style="float: left; width: 70px;"></div>
            <div id="taskbar"></div>
        </div>
    </body>
</html>