<?= $this->doctype()
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <link rel="stylesheet" type="text/css" href="/dhtmlx/dhtmlx.css" />
        <script type="text/javascript" src="/dhtmlx/dhtmlx.js"></script>
        <script type="text/javascript" src="/dhtmlx/connector.js"></script>
        <script type="text/javascript" src="/application.js"></script>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?= Translator::_('SYSTEM_TITLE')
?></title>
    </head>
    <body onLoad="javascript: init()">
        <div id="desktop" style="border: 1px solid gray;"></div>
        <div id="bar">
            <div id="start" style="float: left; width: 70px;"></div>
            <div id="taskbar"></div>
        </div>
    </body>
</html>