<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <link rel="stylesheet" type="text/css" href="/dhtmlx/dhtmlx.css" />
        <script type="application/javascript" src="/dhtmlx/dhtmlx.js"></script>
        <script type="application/javascript" src="/application.js"></script>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?= Translator::_('SYSTEM_TITLE') ?></title>
    </head>
    <body>
        <script type="application/javascript">var application = new Application();</script>
    </body>
</html>